apiVersion: app/v1
kind: Deployment
metadata:
  name: simple-web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: achar95/kuberneteslanding:1
        name: web-ctr
        ports:
        - containerPort: 8080
